### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by ii5mail**
All errors are resolved except one

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
You haven't committed any actual code here

**Comment by ii5mail** [comment]
> You haven't committed any actual code here
After some changings in  file  \greenpress\apps\greenpress\node_modules\.bin\gp-cli-service-pm2-dev.cmd it is running as but not open browser as it should open the brwoser and run on local host ...
PS D:\Projects\Fiverr\fiverr\greenpress> npm run dev      

> @greenpress/monorepo@2.0.5 dev
> lerna exec npm run dev --scope=@greenpress/greenpress

lerna notice cli v4.0.0
lerna notice filter including "@greenpress/greenpress"
lerna info filter [ '@greenpress/greenpress' ]
lerna info Executing command in 1 package: "npm run dev"

> @greenpress/greenpress@2.0.17 dev
> gp-cli-service-pm2-dev

lerna success exec Executed command in 1 package: "npm run dev"
PS D:\Projects\Fiverr\fiverr\greenpress>

**Comment by davidmeirlevy** [comment]
Where is the code of it?

**Comment by ii5mail** [comment]
code of file gp-cli-service-pm2-dev.cmd 
@ECHO off
:find_dp0
SET dp0=%~dp0
EXIT /b

:Start

SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)


@REM "%_prog%" "%dp0%\..\..\..\..\packages\pm2-launcher\bin\dev"   %*
"%_prog%" "%dp0%\..\..\..\..\packages\pm2-launcher\bin\dev" %*

**Comment by davidmeirlevy** [comment]
Please create a proper PR with the code.

**Pull request closed without merging**
