### PR TITLE
add rust gateway

### PR DESCRIPTION
**Pull request by benukhanov**

### CODE REVIEW

**Review by davidmeirlevy — APPROVED** [review]

**Comment by davidmeirlevy** [comment]
Notice that we have a global docs on the main directory of the repository.
You can add documention there, and it will automatically deploy to docs.greenpress.info

**Comment by benukhanov** [comment]
> Notice that we have a global docs on the main directory of the repository.
> You can add documention there, and it will automatically deploy to docs.greenpress.info

Can you please tell me where exactly? I don't see where to add the docs (readme, right?).

Btw, do you prefer squash or rebase? Whatever you prefer, please do it because I don't have an option to do it.

**Comment by davidmeirlevy** [comment]
> > Notice that we have global docs on the main directory of the repository.
> > You can add documentation there, and it will automatically deploy to docs.greenpress.info
> 
> Can you please tell me where exactly? I don't see where to add the docs (readme, right?).
> 
> Btw, do you prefer squash or rebase? Whatever you prefer, please do it because I don't have an option to do it.

1) go to https://docs.greenpress.info
it's the docs that exist at the main `docs` directory.  if you have anything to elaborate on about this rust-gateway, feel free to add to that docs.

2) in this case - squash.

**Comment by benukhanov** [comment]
> > > Notice that we have global docs on the main directory of the repository.
> > > You can add documentation there, and it will automatically deploy to docs.greenpress.info
> > 
> > 
> > Can you please tell me where exactly? I don't see where to add the docs (readme, right?).
> > Btw, do you prefer squash or rebase? Whatever you prefer, please do it because I don't have an option to do it.
> 
> 1. go to https://docs.greenpress.info
>    it's the docs that exist at the main `docs` directory.  if you have anything to elaborate on about this rust-gateway, feel free to add to that docs.
> 2. in this case - squash.

1. Cool, currently I don't think I have to add there something.
2. Feel free to do it. :smiley:

**Pull request merged**
