### PR TITLE
Convert API-kit to TypeScript

### PR DESCRIPTION
**Pull request by CamelJohn**
## Started converting api-kit to typescript.

**Note**: I know someone else is assigned to this - just working the task for fun.

- [ ] `callInternalService` - the **options** seems to only contain an optional url ? (are there more options ? if so they should be defined in the respective interface).

- [ ] `body-parser` - express has a love/hate relationship w/ this one. at the moment it would seem they are quite happy togather ,so i did not use `body-parser` but the built in parsers that **express** has to offer.

- [ ] `body-parser` - i ran into an indexing issue while trying to dynamically access the relevant function/middleware (due to typescript definitions) - so instead i created a manual mapper (in /helpers). not sure that this is the right way.

- [ ] `tsconfig.json` - needs some work, it's not configured past the defaults, the **rootDir** and the **outDir**.

- [ ] `package.json` - added a **build** command, not sure that this is needed ?

### CODE REVIEW

**Comment by CamelJohn** [comment]
ok so a first epic fail on the checks.
will debug these later.

**Comment by davidmeirlevy** [comment]
Hi,

Thanks for the commit!

Notice that you used the old version of greenpress, instead of the latest version with the monorepo.

**Comment by CamelJohn** [comment]
is the up-to-date monorepo in the same repo on a different branch or is it
a whole other repo ? (i could only see like 7 repos).

also i just cloned the repo, dunno if that matters :)

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by CamelJohn** [comment]
> Hi,
> 
> Thanks for the commit!
> 
> Notice that you used the old version of greenpress, instead of the latest version with the monorepo.

Fixed that.  also, I ran the one-off script I created for this PR: https://github.com/greenpress/greenpress/pull/113.

Just a refresher - it takes the dependencies and puts the keys in an array for the `bundledDependencies` field in the respective package.json (for apps).

This is untill lerna merges the issue you flagged.

**Comment by davidmeirlevy** [comment]
looks like a clone of a PR i already merged.

**Pull request closed without merging**
